### ISSUE TITLE
Add notes for facilitators

### ISSUE THREAD

**Issue by dcwalk** [datatogether/reading_datatogether#17]
(from my email:

- come having thought about the texts
- write up 2-4 "themes" or questions you are interested in from the readings
- keep time (and gently wrap is up toward next week)
  - can throw to me or matt p. in terms of why commons/set up for next month if you want
- ask for someone to take notes...

pad we use: https://hackmd.io/oEcuKALCTi-PbawLmT_Ixw#)

**Comment by Mr0grog** [comment]
Can/should we add these to the bottom of the readme? They sound like some good guidelines to me.
