### ISSUE TITLE
Collect open themes/hot topics/futures

### ISSUE THREAD

**Issue by dcwalk** [datatogether/reading_datatogether#31]
To aid with with planning the next round of reading we should collect the open themes/topics/futures!
Add below

From sessions:

- [2: Ownership](https://github.com/datatogether/reading_datatogether/blob/master/notes/2-ownership-2018-07-24.md)
  - from Platform Co-op reading sanctuary and enclosure: "debasing history" and web archives (privacy and sanctuary and enclosure)
  - collective ownership
  - how "decentralized" as a solo term of art is unhelpful
- [3: Commons](https://github.com/datatogether/reading_datatogether/blob/master/notes/3-commons-2018-08-21.md)
  - knowledge commons as a follow up topic: building aqueducts and maintaining bridges - knowledge as a commons that requires maintenance?
    - Potential reading? Intro/chapter one from Understanding Knowledge as a Commons
  - Cycles of tech history and patterns/cycles of centralization
    - Potential reading? Tim Wu "The Master Switch"
- [4: Centralization vs. Decentralization](https://github.com/datatogether/reading_datatogether/blob/master/notes/4-centralization-2018-09-04.md)
  - Affordances, something to take with us and ponder
  - Something about scale
  - What are Accountabilities?
    - Feminist Science Studies
    - Lucy Suchman "Located Accountabilities in Technology Production"
    - Escobar "Design for the Pluriverse" maybe?
- [5: Privacy](https://github.com/datatogether/reading_datatogether/blob/master/notes/5-privacy-2018-09-25.md)
  - A History of Private Life: http://www.hup.harvard.edu/collection.php?cpk=1094
  - Resistance v. Recovering Autonomy (around building a right to loiter, a reparation to public space)
    - Related: politics of refusal
  - peer-to-peer / peer production
- [6: Justice](#)
  -

**Comment by dcwalk** [comment]
Topics around data that came up that I don't think I've explicitly mentioned above are:
  - custody // post-custodial data stewardship
    - https://www2.archivists.org/glossary/terms/p/postcustodial-theory-of-archives
    - https://library.stanford.edu/sites/default/files/Univ%20of%20Texas.pdf
  - trust // trustworthy repositories 
    - http://www.dcc.ac.uk/resources/repository-audit-and-assessment/trustworthy-repositories
  -  data lifecycles
    - https://publiclab.org/notes/warren/07-01-2014/reimagining-the-data-lifecycle
    - "Deconstructing the data life-cycle in digital humanitarianism; Silke Rotha and Markus Luczak-Roesch" https://doi.org/10.1080/1369118X.2018.1521457

**Comment by flyingzumwalt** [comment]
I plan to be reading up on Network Science, like a selection from http://barabasi.com/publications/24/network-science plus some of the related/cited papers

**Comment by dcwalk** [comment]
These have moved to our retrospective doc for now! https://docs.google.com/document/d/1OCjnmQYA-YE0FmpagnLf3qA1IEeNz9fuIoYUONw7CUg/edit#heading=h.5vuc178cz60r
