### ISSUE TITLE
Alternatives to Capitalist Structures (June)

### ISSUE THREAD

**Issue by Frijol** [datatogether/reading_datatogether#41]
Exploring this subject/prepping June reading group selections. Suggestions & ideas welcome.

## Readings
(Checked means someone has read it & can assess value):

### Challenging the status quo
* [x] [The Problem with Work](https://www.goodreads.com/book/show/12741441-the-problem-with-work) p42-47 a helpful intro to the topic (the whole book is great) [Intro 5-8, sec. p51-57]
* [ ] [Post-Work: The Wages of Cybernation](https://www.goodreads.com/book/show/969574.Post_Work)
* [ ] Something on the 1933 30-hour work week bill that passed the Senate? [tangential](https://www.nytimes.com/1971/09/26/archives/justice-black-champion-of-civil-liberties-for-34-years-on-court.html)
* [ ] Capital (Marx)
* [ ] Something about working within the status quo e.g. [80k hours](https://80000hours.org/) or Josh Vial essay

### Universal Basic Income
* [ ] Universal Basic Income as welfare reform & similar– articles
  * [ ] [The Atlantic](https://www.theatlantic.com/international/archive/2015/09/welfare-reform-direct-cash-poor/407236/)
  * [ ] [Journal of Development Economics](https://www.sciencedirect.com/science/article/pii/S0304387813001715)
  * [ ] [Vox on GiveDirectly](https://www.vox.com/2016/4/14/11410904/givedirectly-basic-income)
  * [ ] [GiveDirectly's presentation of the evidence](https://givedirectly.org/research-on-cash-transfers)– source studies from the bib?
* [ ] [Y Combinator (VC) funding research on UBI](https://blog.ycombinator.com/basic-income/)– what has come of that so far?
* [ ] Missing from this list: UBI not intended as welfare

### Other strategies
* [x] Potlatch/potluck: [Potlatch brief history](https://www.thecanadianencyclopedia.ca/en/article/potlatch) | [Nuxalk potlatch](http://nuxalknation.ca/government/potlatch/) | [Potluck Wikipedia page](https://en.wikipedia.org/wiki/Potluck)
* [ ] Missing from this list: studies & theory around gift economies
* [ ] Enspiral practices (find specific articles on ways they've tried collective/business community support)
* [ ] Missing from this list: co-ops and communes, generally
* [ ] Missing from this list: volunteerism, open source contribution
* [x] [SustainOSS 2017 Report](https://sustainoss.org/assets/pdf/SustainOSS-west-2017-report.pdf)
* [x] Nadia Eghbal: [her first Helium Grant post](https://medium.com/@nayafia/5-000-no-strings-attached-9e7b95d33e50) and [other writing](https://nadiaeghbal.com/posts/)

### Visions from fiction
* [x] [Walkaway](https://www.goodreads.com/book/show/40604388-walkaway?from_search=true) [excerpt](https://www.tor.com/2017/04/03/excerpts-cory-doctorow-walkaway-chapter-2/) (“It doesn’t work at all in theory. In theory, we’re selfish assholes who want more than our neighbors, can’t be happy with a lot if someone else has a lot more. In theory, someone will walk into this place when no one’s around and take everything. In theory, it’s bullshit. This stuff only works in practice. In theory, it’s a mess.”)

## Quotes & Notes

* Marx, in Capital, discussed on p6 of Weeks' The Problem with Work "one consents to give the other his or her labor power for a limited period of time, and in return, the other agrees to pay the first a specific amount of money. But to see what happens after the employment contract is signed, the analysis must then move to a different location, the site where this special commodity will be 'consumed'..." 5, 6 "the activity of labor and the social relations that shape, direct, and manage it- will be revealed as the locus of capitalist valorization"
* Glazer: work as the product of education, binary metric of mental and physical wellness (from [her book](https://www.goodreads.com/book/show/6244371-women-s-paid-and-unpaid-labor) referenced in Weeks)
* Gentry: more respect if no need to work
* Postone (Weeks, 8) "on a deep, systemic level, production is not for the sake of consumption"
* The Future is Now chapter of Weeks: posits spectrum from utopia > manifesto > utopian demand sliding from ideal w/o action > concrete demand in the direction of (but not achieving) an ideal

**Comment by dcwalk** [comment]
I'n not sure how to best participate on the comment above, should I check the stuff I've read? (A chunk), how do you want suggestions/additions handled?

**Comment by dcwalk** [comment]
## Visions from Fiction

- The Dispossessed, Ursula K. LeGuin
- New York 2140, Kim Stanley Robinson

**Comment by Frijol** [comment]
I really like all of your ideas. I want to read all of this stuff! I think you're right that in large part we should lean on selections from analyses in order to make the reading list manageable/dive in on smaller passages of closer-to-primary-source materials.

For stuff I've listed that you've read, checkmarks + annotation would be helpful.

I have a lot of reading to do – I'm very interested in this topic but haven't previously taken an academic approach to it

**Comment by Frijol** [comment]
Status update, here's what I'm currently thinking for the core reading:

* The Problem with Work pp 5-8, 42-47, 51-57 @dcwalk any chance you have access to some digital form of this?
* Gibson-Graham, J.K. and E. Miller. 2015. "Economy as Ecological Livelihood" [free pdf](http://www.communityeconomies.org/publications/chapters/economy-ecological-livelihood)
* Frase, Peter. "Four Futures" [free article](https://www.jacobinmag.com/2011/12/four-futures/)
* Silvia Federici interviewed in Mask Magazine [free article](http://www.maskmagazine.com/the-control-issue/struggle/interview-silvia-federici)
* The Cooperative Principles, the Common Good, and Solidarity [free](http://www.geo.coop/story/cooperative-principles-common-good-and-solidarity)

Still looking into:
* A good read on of potluck/potlatch, apparently there's a good description in the intro to Haa Toowu naagu yís
* Pick probably one of the modern techie-idealist reports from Other Strategies above, probably the [Sustain OSS report](https://sustainoss.org/assets/pdf/SustainOSS-west-2017-report.pdf)

Not-required but great/fun reading:
* Walkaway (novel) by Cory Doctorow
* The rest of The Problem with Work

**Comment by dcwalk** [comment]
This looks great!
Question... what are you hoping to get at with a potluck/potlach selection?
Maybe we could include chapter from Red Skin, White Masks, I was just reccomended the section on Dene nation and self-determination (maybe too far?)

Also, selection from [Designs for the Pluriverse](https://www.dukeupress.edu/designs-for-the-pluriverse/) or maybe Anita Say Chan's [Decolonial Computing article](https://catalystjournal.org/index.php/catalyst/article/view/29844) in Catalyst (verry short but great!)

**Comment by dcwalk** [comment]
Brainwave ~~ what about adrienne marie brown's Emergent Strategy ~~ I really loved it. Something from the first half would be excellent to think about shaping futures and drawing on Black feminist thought! And SF!

**Comment by Frijol** [comment]
I just read Emergent Strategy (and I'm gonna go see her next week! She's speaking at the Seattle Library) but not sure what part makes sense for this. Something to do with the community she was living in? It would be great to get something out of Octavia's Brood, length-wise, but also don't have a particular story in mind. Or maybe grab a chapter from Walkaway (the one [this excerpt](https://www.tor.com/2017/04/03/excerpts-cory-doctorow-walkaway-chapter-2/) comes from? I really loved Brown's emphasis on the importance of SF/the imaginary as integral to future-building and activism and want to incorporate.

I've been meaning to read Red Skin, White Masks– do you happen to have a copy? It's not in my library's digital collection.

Re potluck/potlatch, springs from a conversation with @lightandluck – he was talking about how when you have a potluck, everybody brings a dish, and then at the end.. there are always leftovers! A community of abundance. That, and you're proud if your dish comes home empty. I wanted to tie back to potlatch (apparently it's not clear-cut whether potluck derives from that or not) b/c the principle is similar: the wealthiest is the one who gives the most away. It's a bit more nuanced than that & I'm hoping some of the oral traditions literature gives an entry point that backs up the impressions I have from my Tlingit aunts.

**Comment by dcwalk** [comment]
For Emergent Strategy: I was thinking two chapters (~40 pages but fairly fast): **resilience** and **creating more possibilities**

**Comment by Frijol** [comment]
Just read that section of **Designs for the Pluriverse** you linked (so good! Want to read the whole thing but it's not in my library systems :'( ).

For **Emergent Strategy** I'm a bit worried about overloading people with reading (though that book is a quick read). I do want to make sure we include the bit on **p47** on "unlearning socialization"

Altogether, here's how I see our current reading list:

### Core readings
* **Emergent Strategy** (Resilience and Creating More Possibilities? Something smaller?) (40 pages)
* **The Problem with Work pp 5-8, 42-47, 51-57** (14 pages)
* **Silvia Federici interviewed in Mask Magazine** [free article](http://www.maskmagazine.com/the-control-issue/struggle/interview-silvia-federici) (3 pages)
* [This excerpt](https://www.tor.com/2017/04/03/excerpts-cory-doctorow-walkaway-chapter-2/) from the novel **Walkaway** by Cory Doctorow (12 pages)
* Gibson-Graham, J.K. and E. Miller. 2015. "**Economy as Ecological Livelihood**" [free pdf] (7 pages)(http://www.communityeconomies.org/publications/chapters/economy-ecological-livelihood)
* Frase, Peter. "**Four Futures**" [free article](https://www.jacobinmag.com/2011/12/four-futures/) (14 pages)
* **The Cooperative Principles, the Common Good, and Solidarity** [free](http://www.geo.coop/story/cooperative-principles-common-good-and-solidarity) (9 pages)
* Escobar **Designs for the Pluriverse** intro **p7-21** (14 pages)

### Optional readings
* All of Doctorow's novel **Walkaway**
* Dauenhauer. **Haa Tuwunáagu Yis** on potlatch (jsoo.éex’) **p 75-109**

That's a total of 113 pages of core reading– most of it not too dense, but not sure what our benchmark is. What do you think?

**Comment by dcwalk** [comment]
The selection looks awesome. I think it is too long though, the previous two sessions are around ~60 pages core plus optionals.

What if we make Emergent Strategy optional?

**Comment by Frijol** [comment]
That makes sense! I'll make the PR.

**Comment by Frijol** [comment]
Another good section (optional? next semester?): Andy Stern [Raising the Floor](https://www.goodreads.com/book/show/25898100-raising-the-floor) on labor & UBI & the future of work– p171-183 are probably the most relevant

**Comment by Frijol** [comment]
Now reading Debt by David Graeber, which speaks directly to original alternatives to money, to corporations, to capitalism, and the inception of each of these institutions. The end of Chapter 10 and transition into Chapter 11 (and especially Chapter 11 after the section on Cortez) is most relevant
