### ISSUE TITLE
Civics (May) Readings

### ISSUE THREAD

**Issue by dcwalk** [datatogether/reading_datatogether#45]
Let's use the top level of this issue to refine our list of readings and theme description

Theme:

Provisional Reading list:
- [something on "civic" as concept -- or more like "civil society"]
- Paul Frazee [Information Civics](https://infocivics.com/)
- [something to trouble civic vs. citizen vs. community]
- OPTIONAL Johnson, P., & Robinson, P. (2014). Civic hackathons: Innovation, procurement, or civic engagement?. Review of Policy Research, 31(4), 349-357. https://onlinelibrary.wiley.com/doi/full/10.1111/ropr.12074 -- Intro, Conclusion, skim the rest

Dump of [our previous notes](https://docs.google.com/document/d/1KQZ7fJgrr8y23wkNHTXT1N9BXnqPSL2Ub3P19eKZ3YU/edit):

- Plato: Republic (selection) … and other essential foundational readings on the topic of civics
- Digital Civics
- Paul Frazee on “Information Civics”
- Civic vs. citizen vs. community

**Comment by dcwalk** [comment]
## Digital Civics

- magazine article: 
Olivier, P., & Wright, P. (2015). Digital civics: taking a local turn. interactions, 22(4), 61-63.
[download :page_facing_up: ](http://delivery.acm.org/10.1145/2780000/2776885/p61-olivier.pdf?ip=138.51.243.94&id=2776885&acc=ACTIVE%20SERVICE&key=FD0067F557510FFB%2E148C9AE997532579%2E4D4702B0C3E38B35%2E4D4702B0C3E38B35&__acm__=1552590364_8c0e9636310fed1d104161ca63895e76)
- paper: Boehner, K., & DiSalvo, C. (2016, May). Data, Design and civics: an exploratory study of civic tech. In Proceedings of the 2016 CHI Conference on Human Factors in Computing Systems (pp. 2970-2981). ACM.  https://dl.acm.org/citation.cfm?id=2858326
- paper: Asad, M., & Le Dantec, C. A. (2015, February). Illegitimate civic participation: supporting community activists on the ground. In Proceedings of the 18th ACM Conference on Computer Supported Cooperative Work & Social Computing (pp. 1694-1703). ACM.  https://dl.acm.org/citation.cfm?id=2675156

**Comment by dcwalk** [comment]
## Civic Tech

- Matt Stempeck and Micah L. Sifry  Knowledge from failure: learnings from the Civic Tech Field Guide [watch video :movie_camera: ](https://tictec.mysociety.org/2018/presentation/knowledge-from-failure)
- Liz Barry, vTaiwan: Public Participation Methods on the Cyberpunk Frontier of Democracy https://civichall.org/civicist/vtaiwan-democracy-frontier/
- Navigating the field of civic tech: A guide for newcomers and explorers https://medium.com/tradecraft-traction/navigating-the-field-of-civic-tech-c1f9670c8f69
- :hot_pepper:  Johnson, P., & Robinson, P. (2014). Civic hackathons: Innovation, procurement, or civic engagement?. Review of Policy Research, 31(4), 349-357. https://onlinelibrary.wiley.com/doi/full/10.1111/ropr.12074

**Comment by dcwalk** [comment]
## Troubling Civic, Citizen, Community

- Nyers, P. (2010). No one is illegal between city and nation. Studies in social justice, 4(2), 127. https://journals.library.brocku.ca/index.php/SSJ/article/view/998
- http://nooneisillegal.org/  https://en.wikipedia.org/wiki/No_one_is_illegal
- https://www.theguardian.com/us-news/2015/dec/06/illegal-immigrant-label-offensive-wrong-activists-say

**Comment by titaniumbones** [comment]
# Civic as a Concept

-  Iseult Honohan, *[Civic Republicanism](https://books.google.ca/books?hl=en&lr=&id=a0eFAgAAQBAJ&oi=fnd&pg=PP1&dq=philosophy+civic&ots=KnL-SRACHF&sig=XYtkxKAjzY7vqheMWBWl6rz5TyI#v=onepage&q&f=false)* looks somewhat interesting
- Costa, "[Rawlsian Civic Education](https://onlinelibrary-wiley-com.myaccess.library.utoronto.ca/doi/full/10.1111/j.0264-3758.2004.00259.x)", _Journal of Applied Philosophy" 21:1 2004 

- Stanford Enc. of Phil, "[Civic Education](https://plato.stanford.edu/entries/civic-education/)"

**Comment by dcwalk** [comment]
Syllabus on "Civic Studies" seems interesting: https://peterlevine.ws/?p=13298
Some potentials?

- John Dewey, [The Public and its Problems](https://archive.org/details/in.ernet.dli.2015.190550), Chapter 5, “Search for the Great Community.” (too far?)
- Myles Horton and Paulo Freire, We Make the Road by Walking, pp. 115-138
- Jean L. Cohen, “American Civil Society Talk,” in Robert K. Fullinwider, ed., Civil Society, Democracy, and Civic Renewal, pp. 55-85 <-- maybe the closest?
 or this intro from the book of Cohen's: "[Civil Society and Political Theory By Jean L. Cohen, Andrew Arato](https://books.google.ca/books?hl=en&lr=&id=gPvk-eE7t0IC&oi=fnd&pg=PR7&ots=kh7L4vXXKV&sig=8ArNjYYg9M836VNXY765YR2AvFo#v=onepage&q&f=false)"

**Comment by dcwalk** [comment]
Using the term "civil society" might be easier:
- http://www.oxfordhandbooks.com/view/10.1093/oxfordhb/9780195398571.001.0001/oxfordhb-9780195398571-e-1
- https://www.beyondintractability.org/essay/civil-society
- Ehrenberg, J. 1999. Civil Society: The Critical History of an Idea. New York: NYU Press.
