### ISSUE TITLE
Knowledge Commons Blog Post– Next Steps

### ISSUE THREAD

**Issue by Frijol** [datatogether/reading_datatogether#50]
I wrote a [blog post](https://docs.google.com/document/d/1otR9YUXe4jRaj2lX84yqBazB5q4oinZ53QLeZuvbTls/edit#heading=h.n2pkfz4bgp12) from the first DT reading group of the semester! We talked about it a bit [at the end of the Civics call](https://youtu.be/YUt2PxRZCYs?t=4602) & @b5 suggested we continue the conversation asynchronously.

Based on our discussions so far, it sounds like we want to move this toward publication 💫 

So– what's next?

Blog post basics:
* Edits and comments– you should all be able to suggest & comment, and your feedback is welcome– particularly, please edit and approve anything attributed to you! (In general, I'd love to move content-specific discussion into the Google doc)
* What's the process we'd like to adopt for approval & posting to the blog? What kind of timeline do we want to work toward with this? (Also: is there a blog to post to, or are we starting one?)
* Authorship– EDGI Protocol has much to say here, but I'd like help figuring it out. Do we want to use that same authorship protocol?

More ideas:
* @titaniumbones suggested it would be good to add additional context & quotes - yes please!
* @ebarry suggested adding discussion questions for other groups to adopt - also yes please!
* @meiqimichelle reminds us that perfect is the enemy of good– I'm on board with this & would like to put something out in the world! We can improve as we go.
* Someone (@Mr0grog?) asked about intended audience, and that does seem worthy of discussion at some point. Jake mentioned that even something as simple as a summary would help make this more publicly accessible

I'm happy to collaborate & keep building this with any of you who have time in the near future. But I'd also like to get it published without too much ado! We're doing these reading groups monthly, and I'm planning to get started writing the next post in the next week :)

cc also @ericnost @rgardaphe @dcwalk @lightandluck (with apologies to anyone I've missed or ideas not highlighted)

## But here's the key question:
**What do you all think are the right/necessary steps between here and publication?**

**Comment by ebarry** [comment]
I'd like us to consider introducing anything we post with a "You can do this with your collaborators!" frame that would:
* introduce the theme
* link to selected readings
* link to a notes document template with themes, definition of terms, and discussion questions

Perhaps we could ask people to link their own discussion notes back here (somewhere?) with any top level points they'd like to share out to all pursuing the theme. 

Experiments with decentralizing tough discussions to other groups of close collaborators, then sharing back learnings to a broader interested public! Interested to hear more ideas and improvements toward this.

**Comment by Mr0grog** [comment]
> Someone (@Mr0grog?) asked about intended audience

Definitely not me (passing the buck to @dcwalk…?), though I think it was a good point.

**Comment by ericnost** [comment]
+1 to all this. In terms or process and timeline, it seems we'd want to publish before the next month's scheduled reading. 2 weeks to decompress and put together a draft, 1 week for everyone to offer additions/context/etc., and 1 week to finalize and post???

**Comment by lightandluck** [comment]
We should also link to video. Jake said he watched "Knowledge Commons" and it interested him enough to join "Civics".

- Approval: I think we can follow the [governance doc](https://docs.google.com/document/d/1Xpj0lXiIKMKIuvQe4acXFy7bM4t1OYvBH0v1ZLqeCGg/edit#heading=h.o4u2jzkvo4lf) for quotidian decisions and just get a thumbs up from a representative from each Partner. 
I don't think we should get consensus from each person quoted because that would take forever. Individuals should have their say during the editing/commenting phase. So making sure ample notice and time to do so is important, but we should be ok with a deadline!

- Authorship: Think it should be whoever put work into the draft and anybody who spent time editing & wants to be noted, then just slap a `Data Together` on the end.

**Comment by jmitchell** [comment]
> Authorship– EDGI Protocol has much to say here, but I'd like help figuring it out. Do we want to use that same authorship protocol?

Is there somewhere I can learn more about EDGI Protocol? I found [this issue](https://github.com/edgi-govdata-archiving/edgi-website/issues/26) to make it public. I imagine this is mostly in EDGI's hands, but let me know if it would help to have somebody on the outside go over any of it.

**Comment by Frijol** [comment]
Thanks folks! Attentive to the challenges of cadence, here's a proposed timeline for this post:

* By **5/21**: Please submit any comments/edits via suggestion mode on the Google Doc. Additional content is absolutely welcome! Suggestion mode is important because I'm going to turn it back into Markdown for posting purposes
* By **5/28**: I'll make sure that feedback is incorporated & a final draft (including authorship listing) is sent around via the Data Together email lists in the form of a PR (into a new folder on this repo? A new "blog" folder on the website repo? Help me out on figuring out where makes sense to publish?). Per @lightandluck's mention of our existing approval process for quotidian decisions, official approval looks like a PR "approve" review from someone from each of EDGI, QRI, and Protocol Labs
* By **6/4**: Blog gets posted! We also send it out on our Twitter (uh, shouldn't we have a Mastodon account?)!

**Comment by Frijol** [comment]
Currently investigating how to get a blog working on [our hugo site](https://github.com/datatogether/website) with intent to post there after edits (and also using [Rob's GDocs to Markdown conversion tool](https://ipfs.io/ipfs/bafybeiex6klpxcxbnpmili5daklt3qxaqxnuccqubvwoql7d6zvdvv7ukm/))

**Comment by Frijol** [comment]
Heads up that in the future I'll just collect comments & edits on a hackmd so as to avoid markdown > gdocs > markdown!
