### ISSUE TITLE
Stewardship (July) Readings

### ISSUE THREAD

**Issue by lightandluck** [datatogether/reading_datatogether#52]
Gathering readings for July. Please drop anything that might be worth looking at into this issue. 

/cc @Frijol @meiqimichelle

**Comment by Frijol** [comment]
I suspect that this topic was chosen to look at data stewardship, but I keep being drawn to ideas around stewarding the humans that work on that problem.

These two reports tie together both of those to some extent + are strongly reminiscent of the themes we've already touched on in this group:
* Eghbal: [Roads and Bridges: The Unseen Labor Behind Our Digital Infrastructure](https://www.fordfoundation.org/media/2976/roads-and-bridges-the-unseen-labor-behind-our-digital-infrastructure.pdf) - this is sooo good and hits a lot of sore points e.g. "Until that moment, he had 'always assumed, (as had the rest of the world) that the OpenSSL team was large, active, and well resourced.' In reality, OpenSSL wasn’t even able to support one person’s work."
* Nickolls: [Sustain: a One Day Conversation for Open Source Software Sustainers: The Report](https://sustainoss.org/assets/pdf/SustainOSS-west-2017-report.pdf)

More in the direction of archivists & challenges to the mechanics of stewarding data:
* Lippincot: [Environmental Scan of Government Information and Data Preservation Efforts and
Challenges](https://drive.google.com/open?id=1pZSyRqhS_gK9qHXHYjAVEsxheaNhjszb)
* Matheson: [Preservation of Electronic Government Information: An Urgent National Priority](https://drive.google.com/file/d/1P1NzS8y-NTcOAZj_wo5SVX2bGvjvH4oH/view)
* These resources are pointed to by the [PEGI Project National Forum Summary and Report](https://educopia.org/wp-content/uploads/2019/05/PEGIFinalForumSummaryandReport_formatted_20190417.pdf)

(Let me know if you have access to those? Not sure what their permissions are)

It would be really cool to round this stuff out with something more data-justice-y. [This is an example](https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1475-6773.2010.01140.x) of what I mean, though I've only read the abstract and am not a great source in general for data justice stewardship examples (though we def know people who are!)


This topic, like all of the topics we look at, is enormous and could go in a lot of directions. Feel free to use or not use my ideas as you see fit!

**Comment by lightandluck** [comment]
Hi all, this was an enormous topic! I need some help paring this down. I put pdfs of the prospective reading material in a Gdrive. Find everything there: https://drive.google.com/drive/u/1/folders/1K2C3AEf4tdZfMJoyC11RwjX0XwO-Ejtt

I'll eventually trim some of the pdfs and will link to where I got them so they can be properly cited when a list is finalized. Here's the tentative list. I really enjoyed looking back at previous works we didn't delve completely into and thinking about how this topic relates back to previous topics.

## Definition and examples of Stewardship
1. **Pastor Henry Wright - The Stewardship of Time**
   - A lot of what I learned about Stewardship came as a result of my Catholic upbringing. Though I don't prescribe to those beliefs any longer, I agree with Buddhist teaching that something can be learned from anything. Thought this snippet (3 min.) explains how I've continued to understand the basic meaning of being a steward. Link to youtube in the doc. Give it a listen.

2. **for Healing Our Spirit** - I loved these dedications from the book Kelsey recommended
   - "Because We Cherish You ... " SEALASKA Elders Speak To The Future

3. **Tending the Wild** - I really just wanted to include this to think about Indigenous Stewardship of the Land and how that could be transferred to challenges today. It doesn't map completely, but the idea about how _Use_ can improve a commons resource stuck out to me. (There's also a great online series based on the author's work: https://www.kcet.org/shows/tending-the-wild)
    - (xv-xviii): Preface 
    - (2-6): Introduction 
    - (358-364): Coda - Indigenous Wisdom in the Modern World 
- ### Optional
    - a. LTER - Invisible Present Invisible Place
    - b. Leopold-land ethic

## Data Stewardship
4. Theory and Craft of Digital Preservation Draft - Good overview of modern principles, challenges, and opportunities
   - (6-9) - Sixteen Guiding Digital Preservation Axioms
   - (122-130) - Conclusion: Tools for Looking Forward

- ### Optional
    - c. AIMS Born-Digital Collections- An Inter-Institutional Model for Stewardship (1-3)
    - d. FAIR - guiding principles - sdata201618 (1-5)

## Practice and Action
5. Enriching Notion of Data Curation - Case study of *Long Term Ecological
Research (LTER) Network*. Needs to be excerpted. The challenges they've been wrestling with aren't solved yet. We could learn from how they've dealt with things so far. Might be too specific to a group, but I liked learning about their work. Could be removed.

6. hess_ostrom_2007 - **Chapter 9** _Collective Action, Civic Engagement, and the Knowledge
Commons_ - Needs to be excerpted as well. Nice to revisit this title, but could be removed.

7. Post-Custodialism for the Collective Good - Touches on a lot of issues we think about like justice and care. Also, sustaining. Worth reading the whole thing. I liked this a lot! 

## Sustaining 
_(@Frijol - I love the idea of stewarding the stewards, but it might be too much for one session. But, it does feel worthwhile ending up at a place where our group is probably comfortable.)_

8. roads-and-bridges-the-unseen-labor-behind-our-digital-infrastructure - I think the story in the introduction is eye-opening and the opportunities at the end worth including. 
   - (11-17) - Introduction
   - (124-138) - Opportunities Ahead

- ### Optional
    - e. SustainOSS-west-2017-report

/cc @Mr0grog @dcwalk @meiqimichelle

**Comment by Frijol** [comment]
closing per https://github.com/datatogether/reading_datatogether/pull/60

**Comment by Frijol** [comment]
In case we come back to this topic sometime, The Grapes of Wrath ch. 9 (3 pages)
