### ISSUE TITLE
Topic ideas for next semester

### ISSUE THREAD

**Issue by Frijol** [datatogether/reading_datatogether#58]
Collector issue for topics we might discuss in the future– please feel free to add ideas!

Here are a few:

* Trust
* Environmental data justice
* Stoicism
* Algorithmic racism
* Citizenship, moderation, and governance in online spaces
* Ephemerality of digital media/long-term archiving

**Comment by Mr0grog** [comment]
This short piece on moderation for Something Awful vs. YouTube was good: https://www.theverge.com/2019/6/26/18744264/something-awful-youtube-moderation-rich-kyanka-lgbtq

**Comment by lightandluck** [comment]
Oh, in the same vein, this article about Facebook's content moderation is heart-breaking: https://www.theverge.com/2019/6/19/18681845/facebook-moderator-interviews-video-trauma-ptsd-cognizant-tampa

**Comment by lightandluck** [comment]
Something about the problem with secret algorithms:

- Cathy O'Neil - Weapons of Math Destruction: https://www.youtube.com/watch?v=gdCJYsKlX_Y
- https://www.wired.com/story/how-recommendation-algorithms-run-the-world/
- https://www.forbes.com/sites/kalevleetaru/2019/03/07/how-data-scientists-turned-against-statistics/#7ee6c2dd257c

**Comment by lightandluck** [comment]
Community organizing with tech - challenges and pitfalls: 
- https://democracyjournal.org/magazine/45/cyberpower-to-the-people/
- https://medium.com/@elle_mccann/so-you-think-you-want-to-run-a-hackathon-think-again-f96cd7df246a

**Comment by Mr0grog** [comment]
> Environmental data justice

I think this might be better covered as one of the readings or items within a wider “data justice” framing. (Potentially high overlap with some of the other topics, though, especially algorithmic racism.)

**Comment by Frijol** [comment]
Closing because we picked topics for next semester at the DT annual meeting! See https://github.com/datatogether/reading_datatogether/issues/71

Please feel free to open a new issue for 2021 whenever ready.

Here are our [notes](https://docs.google.com/document/d/1-uPPavAgzS0tp9seD4ekLVtAPp54mvkWbD0eK6jxK08/edit#heading=h.hfcp3ei3qrqn), which have many ideas and topics that we *didn't* choose for our 2020 arc– please mine & resurface!
