### ISSUE TITLE
Algorithmic Racism & Environmental Data Justice Readings

### ISSUE THREAD

**Issue by Frijol** [datatogether/reading_datatogether#72]
To be facilitated by @lourdesvera and @rgardaphe. Schedule for 2020 semester here: https://github.com/datatogether/reading_datatogether/issues/71

**How do choices in technology design and implementation reflect and impact broader social structures?  Let's explore, starting with readings from environmental data justice and studies of algorithmic racism.**

We use these issues to solicit additional reading suggestions from the community. **Please add suggestions below!** Ultimately, the facilitators will choose the reading selections for their session.

Here are some readings that were suggested for this topic in the [Data Together Annual Meeting](https://docs.google.com/document/d/1-uPPavAgzS0tp9seD4ekLVtAPp54mvkWbD0eK6jxK08/edit#heading=h.hfcp3ei3qrqn):

* EDJ syllabus: https://docs.google.com/document/d/1O7ytnzXWFkluiYE4Pulo_mCHs9jdNpPm8hw83aLU2pg/edit#
* Algorithmic racism
  * https://www.technologyreview.com/s/612876/this-is-how-ai-bias-really-happensand-why-its-so-hard-to-fix/
  * https://www.technologyreview.com/s/613508/ai-fairer-than-judge-criminal-risk-assessment-algorithm/?fbclid=IwAR1rurQhgCtBmYwQr370x97pZuES5KNbrCf6c8IVbA83xB7BIGYg971Qgdc
* Secret algorithms
  * Cathy O'Neil - Weapons of Math Destruction: https://www.youtube.com/watch?v=gdCJYsKlX_Y
  * https://www.wired.com/story/how-recommendation-algorithms-run-the-world/
  * https://www.forbes.com/sites/kalevleetaru/2019/03/07/how-data-scientists-turned-against-statistics/#7ee6c2dd257c
  * Stewardship in the Age of Algorithms by Clifford Lynch: https://journals.uic.edu/ojs/index.php/fm/article/view/8097/6583

**Comment by lourdesvera** [comment]
Hi all,

I've curated some readings for us to discuss next week. Of course, they are flexible and don't feel pressured to read everything. I chose shorter pieces that get strong messages across in a few words. 

I think it's about 40 pages, but I am putting in mostly websites. I've chosen some selections from the [EDJ Syllabus](https://envirodatagov.org/announcements-rollout-of-environmental-data-justice-syllabus-and-upcoming-ejxyouth-summit-online-event/), which you should check out if you haven't. A lot of the readings do not necessarily have to do with environmental data, but are the data justice offerings that really influenced EDJ as a group. The first is [Sasha Constanza-Chock's essay on Design Justice](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3189696), which is now a book! The academic article of the bunch is [EDJ's extractive logic paper](https://drive.google.com/file/d/14erRGMYNgc6b2iJNwXGGX0leQigFdAHm/view), which is more theoretical. Then, I'm including the [FAIR](https://www.go-fair.org/fair-principles/) and [CARE](https://static1.squarespace.com/static/5d3799de845604000199cd24/t/5da9f4479ecab221ce848fb2/1571419335217/CARE+Principles_One+Pagers+FINAL_Oct_17_2019.pdf) principles from Indigenous Sovereignty Networks. Finally, Pollution is [Colonialism](https://discardstudies.com/2017/09/01/pollution-is-colonialism/) is a short but eye opening blogpost.
