### ISSUE TITLE
Trust Readings

### ISSUE THREAD

**Issue by Frijol** [datatogether/reading_datatogether#74]
To be facilitated by @b5 and @dcwalk. Schedule for 2020 semester here: https://github.com/datatogether/reading_datatogether/issues/71

**New technologies attempt to free us from (data) monopolized spaces, but does cryptographic trust truly map onto or enable better human-to-human (or human-to-company or human-to-technology) trust?**

We use these issues to solicit additional reading suggestions from the community. **Please add suggestions below!** Ultimately, the facilitators will choose the reading selections for their session.

Here are some readings that were suggested for this topic in the [Data Together Annual Meeting](https://docs.google.com/document/d/1-uPPavAgzS0tp9seD4ekLVtAPp54mvkWbD0eK6jxK08/edit#heading=h.hfcp3ei3qrqn): 

* The Dictator’s handbook. 
* Three groups, Winners, People who could become winners, All others
* Trust
* As a crypto concept
* As a basis for community
* https://nbviewer.jupyter.org/github/landmarco/Eviction-Predictor/blob/master/HUD_letter.ipynb?fbclid=IwAR058u_Gj8KbnNQ_9syATGNdVChxyEuDWG7h90jua_cIV7108CJd_Ifws0Y

**Comment by dcwalk** [comment]
I'll jump on to Trust with @b5 if you want the company?

**Comment by b5** [comment]
I'd love the company! 

I don't think I'd be into this as reading group material, but I might be wrong: https://keybase.io/blog/chat-apps-softer-than-tofu

I do find the way that blog post digs in on the UX of trust very interesting

**Comment by dcwalk** [comment]
Great, looking forward to this!

There is a nice description early in [Digital Cash](https://press.princeton.edu/books/hardcover/9780691179490/digital-cash) around trust mechanisms rendered digital which might suit :)

**Comment by Frijol** [comment]
There is some really good stuff in https://dataresponsibly.github.io/courses/spring19/

**Comment by dcwalk** [comment]
from call:
- this phase of trustlessness: first chunk bitcoin whitepaper
- some context on crypto: ch 3 digital cash (maybe another section
- gatekeeping? + trust? and dweb
   - libra article?
- counter- articulation of trust?
   - event to start: https://en.wikipedia.org/wiki/Trust_(social_science)
- "different promises of trust" / trust in context.... 
   - even this report on tech institution trust: https://www.doteveryone.org.uk/report/peoplepowertech2020/

**Comment by b5** [comment]
#### Bitcoin Whitepaper
Here's a link to the white paper. We only need folks to read the introduction: https://bitcoin.org/bitcoin.pdf

#### Techcrunch Article
I definitely think we should read the techcrunch article:
https://techcrunch.com/2015/01/18/after-the-social-web-here-comes-the-trust-web/

I'd love to unpack this quote from the article a bit: 

> At the center of it, trust is shifting from humans and central organizations to computers and decentralized organizations with an underlying decentralized consensus that governs them.

#### dot everyone reading
I think we should skip this one. Reading through it, I think it pivots on the phrase _technology_, while using classical definitions for trust. Unless you saw something in there worth having @dcwalk?

**Comment by b5** [comment]
#### Libra readings
After a bunch of digging, I'd suggest we just go to the source, and read two sections from the updated libra whitepaper: the cover letter, and the section on building an open & competitive network

https://libra.org/en-US/white-paper/#cover-letter
https://libra.org/en-US/white-paper/#an-open-and-competitive-network

Optional third section (mainly just to see how dry this language is):
https://libra.org/en-US/white-paper/#the-libra-association

**Comment by dcwalk** [comment]
I'm still into reading the exec summary of the doteveryone for like a landscape/background overview (maybe we mark this optional?)

Into everything else! PRing:

**Comment by b5** [comment]
Ah good point. I'd skipped the exec summary of doteverything on my second pass. Re-reading it & agree it'd be great to keep as required!

**Comment by b5** [comment]
This was a delightful read regarding Facebook's pivot to "Novi" in place of Libra: https://www.stephendiehl.com/posts/novi.html
