### ISSUE TITLE
Data Monopolies Readings

### ISSUE THREAD

**Issue by Frijol** [datatogether/reading_datatogether#75]
To be facilitated by @jnthnvctr and ~~[? anyone want to co-facilitate?]~~ @titaniumbones . Schedule for 2020 semester here: https://github.com/datatogether/reading_datatogether/issues/71

**Most of our data and information is controlled by a handful of companies. How did this come to be, what are examples of responsible and irresponsible holding of this power, and how do we imagine we might slip the trap of data monopolies?**

We use these issues to solicit additional reading suggestions from the community. **Please add suggestions below!** Ultimately, the facilitators will choose the reading selections for their session.

Here are some readings that were suggested for this topic in the [Data Together Annual Meeting](https://docs.google.com/document/d/1-uPPavAgzS0tp9seD4ekLVtAPp54mvkWbD0eK6jxK08/edit#heading=h.hfcp3ei3qrqn):

* Cory Doctorow’s work: https://boingboing.net/2018/08/09/big-not-tech.html
* https://www.eff.org/deeplinks/2019/07/interoperability-fix-internet-not-tech-companies
* Siva Vaidhyanathan: The Googlization of Everything
* Links to Snapchat from Instagram being banned
* All of facebook’s bad behavior really
* Internet.org  - is there a version of this that is “not bad?” Is there a way to mitigate
https://advox.globalvoices.org/wp-content/uploads/2017/08/FreeBasicsinRealLife_FINALJuly27.pdf
* Google and Getty
https://www.ft.com/content/eda3ea0a-0bc2-11e6-9456-444ab5211a2f
* Some history: 
https://www.newyorker.com/business/adam-davidson/teddy-roosevelt-wouldnt-understand-the-eus-antitrust-fine-against-google
* Stratechery on monopolies aligned with consumers but pressuring suppliers
https://stratechery.com/2017/defining-aggregators/
* Data sovereignty
* Big Tech and Politics today
* Warren
* Yang
* Amazon sidewalk?
* Optionally: ftp://ftp.zew.de/pub/zew-docs/veranstaltungen/rnic/papers/WernhardMoeschel.pdf

--
Maybe goes in here? Closed Source & Its Benefits

* Incentive structures and business models 
* B2C
* Subscription
* Advertising 
* Value attribution of data vs. advertising
* Brave / BAT
* What do business models look like in a Web3 ecosystem coming from web2?

**Comment by dcwalk** [comment]
Watched a super great interview with this person: Matt Stoller (https://mattstoller.com/) who recently wrote "[Goliath: The 100-Year War Between Monopoly Power and Democracy](https://www.indiebound.org/book/9781501183089)". Maybe something to connect to the broader history of monopolies in there

**Comment by lightandluck** [comment]
+1 Matt Stoller - been following him on Twitter and want to read that book as well

**Comment by greggish** [comment]
I'd really like to join this discussion when it happens! And, to add to the mix, I'm thinking about the frame of [Protocols vs Platforms](https://knightcolumbia.org/content/protocols-not-platforms-a-technological-approach-to-free-speech), which threads with Doctorow's recent writing on adversarial interoperability...

**Comment by titaniumbones** [comment]
hi @jnthnvctr looks like we are co-moderating -- let's figure out a way to coordinate & maybe pare down these readings?

**Comment by titaniumbones** [comment]
I think we are on for early may-ish

**Comment by jnthnvctr** [comment]
pinged you on the archivers slack!

**Comment by jnthnvctr** [comment]
**Anti competitiveness, and how did we get here?** 
Modern day monopolies: https://www.wsj.com/articles/why-u-s-businesses-want-trustbusting-11570803088
Teddy Roosevelt Would Not Understand the E.U.’s Antitrust Fine Against Google: https://www.newyorker.com/business/adam-davidson/teddy-roosevelt-wouldnt-understand-the-eus-antitrust-fine-against-google
Anti trust in the EU/US: ftp://ftp.zew.de/pub/zew-docs/veranstaltungen/rnic/papers/WernhardMoeschel.pdf

**What are the things we worry about with monopolies?** 
Economic / social / political bads as outcomes of monopolistic power
https://arstechnica.com/gadgets/2018/02/internet-rages-after-google-removes-view-image-button-bowing-to-getty/
http://press.gettyimages.com/getty-images-files-competition-law-complaint-against-google/

**Data Monopolies in a COVID era?**
Contact tracing and privacy?
https://www.theverge.com/2020/5/1/21243977/gop-senators-contact-tracing-data-coronavirus-covid-19-privacy
Data Privacy bill in response: https://www.commerce.senate.gov/2020/4/wicker-thune-moran-blackburn-announce-plans-to-introduce-data-privacy-bill
Contact tracing proposal from Apple / Google
https://www.blog.google/documents/66/Overview_of_COVID-19_Contact_Tracing_Using_BLE_1.pdf

**Optional bits to play around with for discussion:** 
Can data monopolies be a force for good?
https://dataforgood.fb.com/tools/disease-prevention-maps/
Google/FB/Apple reports about data movement
https://visualization.covid19mobility.org/
More reading on modern monopolies: https://www.newstatesman.com/goliath-matt-stoller-review

**Comment by dcwalk** [comment]
Is this still happening today?

**Comment by Frijol** [comment]
Moved to next week! @dcwalk
