### ISSUE TITLE
Polity Readings

### ISSUE THREAD

**Issue by Frijol** [datatogether/reading_datatogether#77]
To be facilitated by @StefanMorales and @dcwalk. Schedule for 2020 semester here: https://github.com/datatogether/reading_datatogether/issues/71

**Who are the groups of people to whom we are connected in systems of governance? To whom do we owe allegiance?**

We use these issues to solicit additional reading suggestions from the community. **Please add suggestions below!** Ultimately, the facilitators will choose the reading selections for their session.

Here are some readings that were suggested for this topic in the [Data Together Annual Meeting](https://docs.google.com/document/d/1-uPPavAgzS0tp9seD4ekLVtAPp54mvkWbD0eK6jxK08/edit#heading=h.hfcp3ei3qrqn):

--
Maybe goes here: Availability in a peer-2-peer context

* Switching to decentralized techniques levels the client-server relationship, but places new responsibility on clients to “leave their computer on”. Users disconnecting from a decentralized network can make content unavailable. In technical contexts this is  described as a “Network Churn” problem that others are designing technical solutions for.
* Bitswap design
* Filecoin whitepaper, or the design of filecoin as an incentive mechanism for staying connected
* There is also a social side to the availability problem. What are our obligations as digital citizens?
* What about volunteererism? Are p2p networks built on voluteerism? 
* Volunteerism: DataTogether is a volunteer-led organization. How does being volunteer-led shape what an organization can do or do well, or how members or stakeholders engage or collaborate with the organization
* https://onezero.medium.com/the-internet-relies-on-people-working-for-free-a79104a68bcc
* Nadia Eghbal Roads and Bridges!
* From Kevin: Chatting with creator of [Hot Glue](http://hotglue.me/): a simple drag-and-drop web page maker on DAT. Dat has an experimental protocol for chatting with folks who are forking your site. You can only participate in the chat if you’re seeding the web site. Your ability to participate is based on contributing (seeding the site). What opens if the tab is closed? What happens if a person stops seeding, but then seeds again?

--
Maybe goes here: Alternative Organizational Structures
* What is the relationship between an org chart and network topology?
* https://www.youtube.com/watch?v=OqmdLcyES_Q
* Fredric Laloux - Reinventing Organizations https://www.reinventingorganizations.com
* Richard Bartlett: Courage Before Hope: A Proposal to Weave Economic & Emotional Microsolidarity (See also: Scuttlebutt “Faerie Rings”)
* The (potentially problematic) case of Valve Software
* (Would have to find a subsection) The Dictator’s Handbook
* Something from an existing or older culture or practice?
* EDGI & the OAR model
* The maintainers? http://themaintainers.org
* Unions?
* Matt Price on Civilian Conservation Corps as a model to juxtapose with the military:
* “I grew up thinking of the CCC as a model for what a government can do to help people out, and what people can do to turn their energy to the collective good. And, but, or also– it is troubling to think of how much that thinking shares with the military.”
* Co-operative models
* Visions for a better world: can we pull together examples of fragments of society & tech that are really working? What can we learn from these?
* Enspiral Collective: “Better Work Together”
* Concept of the co-op
* B-corps?
* Intrinsically motivated work
* How to Do Nothing by Jenny Odell
* The Mattereum Manifesto: green capitalism, product information markets, and the blockchain

--
Maybe goes here: decentralization & systems thinking

* Decentralization: https://github.com/datatogether/reading_datatogether/issues/64#issuecomment-537154725
* Meadows "Thinking in Systems: A primer"
* Adrienne Marie Brown - Emergent Strategy https://www.goodreads.com/book/show/29633913-emergent-strategy
* Craft of Game Systems: https://www.gamasutra.com/view/news/128271/The_Craft_of_Game_Systems_General_Guidelines.php

--
* Community organizing with tech - challenges and pitfalls:
* https://democracyjournal.org/magazine/45/cyberpower-to-the-people/
* https://medium.com/@elle_mccann/so-you-think-you-want-to-run-a-hackathon-think-again-f96cd7df246a

--
* Stoicism: https://www.nytimes.com/2019/03/26/style/silicon-valley-stoics.html

**Comment by StefanMorales** [comment]
Happy to co-facilitate this one!
S

**Comment by Frijol** [comment]
@dcwalk I think you mentioned in our call you might want to co-facilitate this one?

**Comment by dcwalk** [comment]
I'm able to assist, tho have less context on this topic than others and see myself more in a supporting role. @StefanMorales do you have a vision? maybe we set up a time to chat and pick readings?

**Comment by StefanMorales** [comment]
Hi! Sorry I haven't been able to come to the other reading group sessions! Coming as no surprise, I've had a crazy past few months. I will try to come to the session on July 7th if I'm free then. As for the Polity session, I'm happy to co-facilitate this still, and surprisingly, this topic comes at exactly the right time for me and I'll say why in just a bit. 

First, @dcwalk are there readings you are curious about? I like the prompt "Who are the groups of people to whom we are connected in systems of governance? To whom do we owe allegiance?" I think a broader systems view is helpful to consider the first question, and then the latter question I would expand and modify a bit: "To whom do we owe allegiance, fidelity and solidarity? How?" 

I believe that allegiance has hints of hierarchy, negotiations and power-play, whereas fidelity and solidarity have hints of horizontality, friendship, belonging, class-awareness, etc. And then the question of how we "owe" can also be further troubled a bit to move from a frame of indebtedness of the individual to the group to one of abundance, gifting, offering, etc. where there is more of an interplay between individual and group. In this way, we are connected to many different groups of people in layered systems of governance: some of which are characterized by allegiances owed, and others of which are characterized by the gifts of generative group interaction. 

OK with all that in mind, here's why this comes at a ripe time for me: we are finalizing some critical documents and guidance materials for our self-managed professional services cooperative, INCOMMON. As part of this, we are building our "Minimum Viable Board" agreement as well as our consent decision-making guidelines for facilitators (a role we are rotating through our group). We've used these processes to collaboratively make decisions as a group about the DNA of the org itself. All of this is practice-based work, so I'd be happy to share learnings, and would be also curious to hear about EDGI/Data Together's work within its polity (or the peripheries it is aware of/inspired by). Lastly, I'd also be happy to facilitate the session using liberating structures to help us best leverage our collective input while also retaining the central purpose of a reading group. I'm thinking UX Fishbowl could work with a few of us speaking to our thoughts on readings/experiences, in addition to maybe checking in at the beginning and end using Ecocycle to self-assess how we are interacting with these multiple layers of polity that we are all connected to in various ways. Happy to explore session design further @dcwalk on a call sometime in the next few weeks!

Here are some essential readings/resources, but I'll think on some more and look at the list above soon:
- http://goinghorizontal.co/ (Chapters 3 and 7 of the book)
- https://www.youtube.com/watch?v=HvFZL2tGLiM
- https://www.youtube.com/watch?v=uJG5f4EBGGQ&feature=youtu.be
- https://handbook.enspiral.com/agreements/board.html
- https://handbook.enspiral.com/agreements/catalyst.html
- https://handbook.enspiral.com/agreements/decisions.html

**Comment by dcwalk** [comment]
Hey! apologies for the delay -- just realized this is the same week I'm hosting a conference so I'm definitely not the best co-moderator :sweat_smile:

**Comment by Frijol** [comment]
I've recently been thinking about polity in the context of justice, too, & alternatives to banishment + the carceral state (creating polity boundaries and removing bad actors to "outside" the polity) such as transformative & restorative justice (recognizing harms as rooted in the existing system and asking: how do we as a community/polity learn from the bad thing & adjust so that it cannot occur in the future?)

I don't have great resources for getting at that directly but here is what I found:
* https://www.goodreads.com/quotes/7430240-prisons-do-not-disappear-social-problems-they-disappear-human-beings
* Feeling iffy about co-opting concepts from a smaller religious group but this is one of the practices that springs to mind https://amishamerica.com/shunning/
* https://transformharm.org/transformative-justice-a-brief-description/
* https://truthout.org/articles/building-community-safety-practical-steps-toward-liberatory-transformation/
* http://adriennemareebrown.net/2015/07/09/what-isisnt-transformative-justice/

**Comment by Frijol** [comment]
Separately, and more directly on the concept of polity, this is pretty interesting: https://theconversation.com/indigenous-people-are-a-polity-on-sovereignty-and-constitutional-recognition-44287
and links out to this: https://www.smh.com.au/politics/federal/noel-pearson-slams-advocate-for-modest-indigenous-recognition-20150703-gi4pu2.html which I feel like I need more context to understand but am interested by.

Would perhaps also be useful to directly read Rosseau/The Social Contract

**Comment by StefanMorales** [comment]
Got it @dcwalk thanks for the heads up. @Frijol how is the level activity in the group over the summer? I saw that the last session was low attendance. I'm still available to host the polity session, and could do it with a co-facilitator if someone from the group is available. But I don't want to put in the time and energy if we don't have very many RSVPs. Any thoughts? Push it back to September or October?

**Comment by Frijol** [comment]
Good point! I'll put a poll out on the list to see if we can nail down better dates

**Comment by Frijol** [comment]
@StefanMorales @dcwalk How do you feel about moving this reading session to October 6th?

**Comment by StefanMorales** [comment]
@Frijol  works for me. How about you @dcwalk ?

**Comment by dcwalk** [comment]
That works!

**Comment by StefanMorales** [comment]
@dcwalk want to jump on a call mid-September to talk about readings/themes, etc.?

**Comment by dcwalk** [comment]
Hi! Phew, almost in late Sept. happy to have that call now if you’d still like help coordinating!

**Comment by StefanMorales** [comment]
Hi @dcwalk! Yes, that'd be great. Tho, I think we'll want to push out the date for the reading group so folks can have a chance to read! What do you think @Frijol ? 

As for meeting, @dcwalk how do we connect? I'd be game to talk later this week if you're around. I have flexibility on Friday, but unclear how we share contact info without it being public, etc. on this page... I also need to change my email used for the google group. @frijol is that something I can do, or will you need to do it?

> Hi! Phew, almost in late Sept. happy to have that call now if you’d still like help coordinating!
> […](#)
> On Aug 17, 2020, at 10:43, StefanMorales ***@***.***> wrote: ﻿ @dcwalk want to jump on a call mid-September to talk about readings/themes, etc.? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Frijol** [comment]
Yes, please go ahead and reschedule as needed!

**Comment by dcwalk** [comment]
Format:
Experience LS through practising it: (the way in which we gather differently)
- wise crowds
- spiral
- conversation cafe + reflection activity (drawing together eg..)

**Comment by StefanMorales** [comment]
Polities: Econ means (1-2) -Polities in practice (3short) -Polities re: data together/volunteerism (1-2)

**Comment by dcwalk** [comment]
From email....Volunteerism and polities:
- The Internet Relies on People Working for Free

Polities/economies:
- The Catalan Integral Cooperative: an organizational study of a post-capitalist cooperative

Unlearning conventional microstructures of gathering/agreeing:
- Democracy --> Sociocracy (un)learning individual and group patterns (Youtube)
- Microstructures and Design Elements of Liberating Structures

**Comment by Frijol** [comment]
closed with https://github.com/datatogether/reading_datatogether/pull/95

**Comment by almereyda** [comment]
I might be arriving way past events, hence after diving into *Liberating Structures*, returning down here after reading:

> What is the relationship between an org chart and network topology?

Which, for the attempt of answering, makes me remember Conway's Law, that states

> Any organization that designs a system (defined broadly) will produce a design whose structure is a copy of the organization's communication structure.

with known (= search and findable) corollaries by Shalloway ²:

> When development groups change how their development staff are organized, their current application architecture will work against them.

or indirectly by Coplien and Harrison through Ian Bicking ³ :

> If the parts of an organization (e.g. teams, departments, or subdivisions) do not closely reflect the essential parts of the product, or if the relationship between organizations do not reflect the relationships between product parts, then the project will be in trouble… Therefore: Make sure the organization is compatible with the product architecture

underlined by this comment on the Wikipedia talk page ¹ :

> "Notably, the hypothesis predicts correspondence but does not impose a direction of causality: effects may flow from organizational structure to technical design (Henderson and Clark, 1990); from technical design to organizational structure (Chandler, 1977); or in both directions (Baldwin and Clark, 2000; Fixson and Park, 2007)." 

Now as this originally seems to target software infrastructures, it remains the interesting task to evaluate the materialities and labour conditions of network hardware besides them.

Summa summarum, governing the network topology can be done by [Refactoring an Organisation](http://code.wiki.randombits.xyz/refactoring-an-organization.html)?

<details>

 <summary>Links </summary>

1. [Talk:Conway's law - Wikipedia](https://en.wikipedia.org/wiki/Talk:Conway%27s_law#Notes_on_direction_of_causality)
2. [Conway’s Law and Corollary – Net Objectives Portal](https://portal.netobjectives.com/pages/flex/conways-law-and-corollary/)
3. [Conway’s Corollary](https://www.ianbicking.org/blog/2015/08/conways-corollary.html)
4. [Conway’s Corollary « The Skeptical Methodologist](https://skepticalmethodologist.wordpress.com/2009/01/17/conways-corollary/)
5. [Conway's Law](http://melconway.com/Home/Conways_Law.html)
6. [Committees Paper](http://www.melconway.com/Home/Committees_Paper.html)
7. [Conway's law - Wikipedia](https://en.wikipedia.org/wiki/Conway%27s_law)
8. [Melvin Conway - Wikipedia](https://en.wikipedia.org/wiki/Melvin_Conway)

</details>
